### ISSUE TITLE
Morning Section: 15-01-2020

### ISSUE THREAD

**Issue by Dandush03** [meme-es/videoplayer-page#6]
I Recomend to use the Grid template areas css property and rename all the clases that have the same name of the tags
`.page-setup{
    display: grid;
    grid-template-areas:
    'header header header'
    'left main rigth'
    'left main rigth';
    grid-template-columns: 2% 72% 25%;
}`

**Comment by maosan132** [comment]
Thank you I will check it out!

**Comment by maosan132** [comment]
Done! but I have used an alternative css-grid
